/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.neohope.kk.demo.beans;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TCustomerSchema extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TCustomerSchema\",\"namespace\":\"com.neohope.kk.demo.beans\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"faxNumber\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public int id;
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.lang.CharSequence faxNumber;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public TCustomerSchema() {}

  /**
   * All-args constructor.
   */
  public TCustomerSchema(java.lang.Integer id, java.lang.CharSequence name, java.lang.CharSequence faxNumber) {
    this.id = id;
    this.name = name;
    this.faxNumber = faxNumber;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return faxNumber;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: name = (java.lang.CharSequence)value$; break;
    case 2: faxNumber = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'faxNumber' field.
   */
  public java.lang.CharSequence getFaxNumber() {
    return faxNumber;
  }

  /**
   * Sets the value of the 'faxNumber' field.
   * @param value the value to set.
   */
  public void setFaxNumber(java.lang.CharSequence value) {
    this.faxNumber = value;
  }

  /** Creates a new TCustomerSchema RecordBuilder */
  public static com.neohope.kk.demo.beans.TCustomerSchema.Builder newBuilder() {
    return new com.neohope.kk.demo.beans.TCustomerSchema.Builder();
  }
  
  /** Creates a new TCustomerSchema RecordBuilder by copying an existing Builder */
  public static com.neohope.kk.demo.beans.TCustomerSchema.Builder newBuilder(com.neohope.kk.demo.beans.TCustomerSchema.Builder other) {
    return new com.neohope.kk.demo.beans.TCustomerSchema.Builder(other);
  }
  
  /** Creates a new TCustomerSchema RecordBuilder by copying an existing TCustomerSchema instance */
  public static com.neohope.kk.demo.beans.TCustomerSchema.Builder newBuilder(com.neohope.kk.demo.beans.TCustomerSchema other) {
    return new com.neohope.kk.demo.beans.TCustomerSchema.Builder(other);
  }
  
  /**
   * RecordBuilder for TCustomerSchema instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TCustomerSchema>
    implements org.apache.avro.data.RecordBuilder<TCustomerSchema> {

    private int id;
    private java.lang.CharSequence name;
    private java.lang.CharSequence faxNumber;

    /** Creates a new Builder */
    private Builder() {
      super(com.neohope.kk.demo.beans.TCustomerSchema.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.neohope.kk.demo.beans.TCustomerSchema.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.faxNumber)) {
        this.faxNumber = data().deepCopy(fields()[2].schema(), other.faxNumber);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing TCustomerSchema instance */
    private Builder(com.neohope.kk.demo.beans.TCustomerSchema other) {
            super(com.neohope.kk.demo.beans.TCustomerSchema.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.faxNumber)) {
        this.faxNumber = data().deepCopy(fields()[2].schema(), other.faxNumber);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.Integer getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public com.neohope.kk.demo.beans.TCustomerSchema.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public com.neohope.kk.demo.beans.TCustomerSchema.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'name' field */
    public java.lang.CharSequence getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public com.neohope.kk.demo.beans.TCustomerSchema.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'name' field */
    public com.neohope.kk.demo.beans.TCustomerSchema.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'faxNumber' field */
    public java.lang.CharSequence getFaxNumber() {
      return faxNumber;
    }
    
    /** Sets the value of the 'faxNumber' field */
    public com.neohope.kk.demo.beans.TCustomerSchema.Builder setFaxNumber(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.faxNumber = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'faxNumber' field has been set */
    public boolean hasFaxNumber() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'faxNumber' field */
    public com.neohope.kk.demo.beans.TCustomerSchema.Builder clearFaxNumber() {
      faxNumber = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public TCustomerSchema build() {
      try {
        TCustomerSchema record = new TCustomerSchema();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.faxNumber = fieldSetFlags()[2] ? this.faxNumber : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
